gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

matrix:
  exclude:
  - rvm: 2.2
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.2
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails_6.0.gemfile
